#!/usr/bin/env python3
"""Export one optimised route as a static JSON for the frontend.

The Route subpage calls the live optimiser at ``/api/route``. That endpoint only
exists where the Python runtime is deployed (Vercel), so when the site is opened
from disk or served by ``python -m http.server`` the page falls back to the file
this script writes.

The fallback is built on the *synthetic* nominal wind field from robustness.py
(steady 20 kt from 205 T), not on ``forecast/grib.grb2`` -- reading the GRIB
needs pygrib, which the frontend toolchain does not have. It is a shape-correct
demonstration route, and the page labels it as such.

    python route/export_sample_route.py
"""

from __future__ import annotations

import json
from pathlib import Path

import robustness as B
import route as R

OUTPUT = Path(__file__).resolve().parents[1] / "frontend" / "data" / "route-sample.json"
CURRENT = {"speed": 1.0, "toward": 45.0}
WIND = {"tws_knots": 20.0, "twd_degrees": 205.0}


def main() -> None:
    wind_at = B.synthetic_wind(WIND["tws_knots"], WIND["twd_degrees"])
    polars = R.load_polars()
    result = R.route({"current": CURRENT}, polars, wind_at)
    payload = R.result_json(result, wind_at)
    payload["source"] = "synthetic"
    payload["note"] = (
        f"Sample route: steady {WIND['tws_knots']:.0f} kt from "
        f"{WIND['twd_degrees']:.0f} T, current {CURRENT['speed']:.0f} kt toward "
        f"{CURRENT['toward']:.0f} T. Generated by route/export_sample_route.py "
        "for offline viewing; the live page recomputes against the forecast GRIB."
    )
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(json.dumps(payload, indent=2) + "\n")
    print(f"{len(payload['route'])} legs, {payload['duration_hours']} h -> {OUTPUT}")


if __name__ == "__main__":
    main()
